fail
fail-early
show-error
proto = "=https"
url = "https://localhost:8765/demos/html-observatory/"
url = "https://localhost:20997/v1/health"
url = "https://localhost:20997/v1/ready"
url = "https://localhost:20997/v1/observatory"
