#!/bin/sh
if [ "$CSDLC_CONVERSION_FENCE" != absent ]; then exit 23; fi
printf control >> '/var/folders/rq/nnff0vs91jzfvmb8tjqxtjgc0000gn/T/csdlc-872-1789499468153115000/primary/copied-records/writer-control.log'
