#!/usr/bin/env python3
"""Regenerate the #817 release-status projection from Git and live issue reads."""
from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = next(path for path in Path(__file__).resolve().parents if (path / "AGENTS.md").is_file())
BASE = ROOT / "docs/milestones/v0.92.1"
PACKET = BASE / "evidence/release/current-status"
DOCS = [BASE / f"{name}_v0.92.1.md" for name in (
    "FEATURE_PROOF_COVERAGE", "DEMO_MATRIX", "RELEASE_NOTES", "MILESTONE_CHECKLIST"
)]
FEATURE_OWNERS = {
    "REPO": [522], "CORP": [522], "CSDLC": [522, 817], "DRT": [522, 814],
    "POD": [522, 526], "HOT": [522, 816], "OBS": [522, 816], "DEC": [522],
    "PROV": [522], "GCP-DRT": [522], "AWS": [522, 815], "GCP": [522, 815, 817],
    "XCL": [522, 815], "RUST": [522, 814],
}
CHECKLIST_OWNERS = {"C27": 817, "C33": 816}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git_show_sha(revision: str, relative: str) -> str:
    data = subprocess.check_output(["git", "show", f"{revision}:{relative}"], cwd=ROOT)
    return hashlib.sha256(data).hexdigest()


def issue_observation(numbers: list[int], source: str, observed_at: str) -> dict:
    raw = subprocess.check_output([
        "gh", "issue", "list", "--repo", "agent-logic/agent-design-language",
        "--state", "all", "--limit", "1000",
        "--json", "number,state,closedAt,updatedAt,title,url",
    ], cwd=ROOT, text=True)
    by_number = {row["number"]: row for row in json.loads(raw)}
    missing = sorted(set(numbers) - set(by_number))
    if missing:
        raise SystemExit(f"issue observation missing: {missing}")
    return {
        "schema": "adl.release_issue_observation.v1",
        "repository": "agent-logic/agent-design-language",
        "source_revision": source,
        "observed_at": observed_at,
        "issues": [by_number[number] for number in sorted(numbers)],
    }


def owner_links(owners: list[int]) -> str:
    return ", ".join(
        f"[#{number}](https://github.com/agent-logic/agent-design-language/issues/{number})"
        for number in owners
    )


def update_evidence_map(status: dict, old_source: str, source: str) -> None:
    path = PACKET / "EVIDENCE_MAP.md"
    text = path.read_text().replace(old_source, source)
    text = text.replace("Final documentation refresh for #767, implemented in #799;",
                        "Candidate-bound documentation refresh for #767, regenerated by #817;")
    text = re.sub(r"Exact projection source: `[0-9a-f]{40}`", f"Exact projection source: `{source}`", text)
    for feature in status["features"]:
        start = text.index(f"## {feature['id']}\n")
        following = text.find("\n## ", start + 4)
        end = len(text) if following < 0 else following
        section = text[start:end]
        section = re.sub(r"^Limit: .*?$", f"Limit: {feature['limit']}", section, flags=re.M)
        section = re.sub(r"^Debt owners: .*?$", f"Debt owners: {owner_links(feature['debt_owners'])}.", section, flags=re.M)
        text = text[:start] + section + text[end:]
    path.write_text(text)


def update_docs(status: dict, old_source: str, source: str) -> None:
    header = "| ID | Feature | Delivery | Proof | Demo | Release |\n|---|---|---|---|---|---|\n"
    rows = "".join(
        f"| {row['id']} | {row['name']} | {row['delivery_status']} | {row['proof_status']} | "
        f"{row['demo_status']} | {row['release_status']} |\n"
        for row in status["features"]
    )
    block = f"<!-- release-status:start -->\n{header}{rows}<!-- release-status:end -->"
    for path in DOCS:
        text = path.read_text().replace(old_source, source)
        text, count = re.subn(r"<!-- release-status:start -->.*?<!-- release-status:end -->", block, text, flags=re.S)
        if count != 1:
            raise SystemExit(f"status block denominator: {path}")
        if path.name == "MILESTONE_CHECKLIST_v0.92.1.md":
            checklist = {row["id"]: row for row in status["checklist"]}
            output = []
            for line in text.splitlines(keepends=True):
                match = re.match(r"\| (C\d+) \|", line)
                if match and match.group(1) in checklist:
                    cells = line.rstrip("\n").split("|")
                    owner = checklist[match.group(1)]["owner"]
                    cells[-2] = " None " if owner is None else f" {owner_links([owner])} "
                    line = "|".join(cells) + "\n"
                output.append(line)
            text = "".join(output)
        path.write_text(text)


def main() -> None:
    if len(sys.argv) != 2 or re.fullmatch(r"[0-9a-f]{40}", sys.argv[1]) is None:
        raise SystemExit("usage: refresh-current-status.py <source-revision>")
    source = sys.argv[1]
    subprocess.run(["git", "merge-base", "--is-ancestor", source, "HEAD"], cwd=ROOT, check=True)
    status_path = PACKET / "status.json"
    status = json.loads(status_path.read_text())
    old_source = status["source_revision"]
    observed_at = datetime.now(timezone.utc).isoformat()
    numbers = {row["number"] for row in json.loads((PACKET / "issue-observation.json").read_text())["issues"]}
    numbers.update({814, 815, 816, 817})
    observation = issue_observation(sorted(numbers), source, observed_at)
    observation_path = PACKET / "issue-observation.json"
    observation_path.write_text(json.dumps(observation, indent=2) + "\n")

    open_issues = {row["number"] for row in observation["issues"] if row["state"] == "OPEN"}
    status["source_revision"] = source
    status["as_of"] = observed_at
    status["issue_observation"] = {
        "path": observation_path.relative_to(ROOT).as_posix(),
        "sha256": sha256(observation_path),
    }
    by_feature = {row["id"]: row for row in status["features"]}
    for ident, owners in FEATURE_OWNERS.items():
        by_feature[ident]["debt_owners"] = [owner for owner in owners if owner in open_issues]
        if not by_feature[ident]["debt_owners"]:
            by_feature[ident]["debt_owners"] = [522]
    feature_for_wp = {work: feature["id"] for feature in status["features"] for work in feature["work_packages"]}
    for work in status["work_packages"]:
        work["proof_debt_owners"] = list(by_feature[feature_for_wp[work["id"]]]["debt_owners"])
    for row in status["checklist"]:
        if row["owner"] is not None and row["owner"] not in open_issues:
            row["owner"] = CHECKLIST_OWNERS.get(row["id"], 522 if row["status"] == "blocked" else None)
    for source_row in status["sources"]:
        source_row["revision"] = source
        source_row["sha256"] = git_show_sha(source, source_row["path"])
    status_path.write_text(json.dumps(status, indent=2) + "\n")
    update_docs(status, old_source, source)
    update_evidence_map(status, old_source, source)
    print(json.dumps({
        "status": "refreshed",
        "source_revision": source,
        "issues": len(observation["issues"]),
        "open_issues": len(open_issues),
        "features": len(status["features"]),
        "work_packages": len(status["work_packages"]),
    }, sort_keys=True))


if __name__ == "__main__":
    main()
